#!/usr/bin/env python3
"""Offline tool: bin-pack the Birkholz-Schlegel benchmark into parallel batches.

Reads ``tests/data/birkholz_schlegel/reference.json``, applies a closed-form
runtime cost model per solver, and prints a YAML fragment ready to paste into
the ``strategy.matrix.include`` block of ``.github/workflows/benchmark.yaml``.

Cost model (no wall-time data available; theory-based estimate):

* mopac:  cost(N, s) = N**2 * s   with s = ``mopac_pm7_steps``
* pyscf:  cost(N, s) = N**4 * s   with s = ``paper_steps``  (since
  ``pyberny_steps`` is ``null`` for every molecule, the paper's optimizer
  step count is the only available proxy)

Molecules whose step count is ``null`` get the median step count for that
solver before the formula is applied.

Bin-packing is Longest-Processing-Time-first (LPT): sort by cost descending,
assign each to the bin with the lowest current sum. ``--nbins`` defaults to
``ceil(total_cost / max_single_cost)`` so the heaviest molecule does not
bottleneck the run.
"""

import argparse
import json
import math
import statistics
from pathlib import Path

REFERENCE = (
    Path(__file__).resolve().parents[1]
    / 'tests'
    / 'data'
    / 'birkholz_schlegel'
    / 'reference.json'
)

COST_EXPONENT = {'mopac': 2, 'pyscf': 4}
STEPS_KEY = {'mopac': 'mopac_pm7_steps', 'pyscf': 'paper_steps'}


def costs(reference, solver):
    key = STEPS_KEY[solver]
    steps = [reference[n][key] for n in reference if reference[n][key] is not None]
    fallback = statistics.median(steps)
    p = COST_EXPONENT[solver]
    return {
        n: reference[n]['atoms'] ** p * (reference[n][key] or fallback)
        for n in reference
    }


def pack(items, nbins):
    # LPT: heaviest first, into the currently-lightest bin.
    bins = [[] for _ in range(nbins)]
    totals = [0.0] * nbins
    for name, cost in sorted(items.items(), key=lambda kv: (-kv[1], kv[0])):
        i = min(range(nbins), key=lambda j: (totals[j], j))
        bins[i].append(name)
        totals[i] += cost
    return bins, totals


def plan(reference, solver, nbins):
    c = costs(reference, solver)
    total = sum(c.values())
    biggest = max(c.values())
    if nbins is None:
        nbins = max(1, min(8, math.ceil(total / biggest)))
    bins, totals = pack(c, nbins)
    for b in bins:
        # Small-first within a bin gives readable shard logs.
        b.sort(key=lambda n: reference[n]['atoms'])
    return bins, totals, nbins


def emit(reference, solvers, nbins_arg):
    out = []
    out.append('# Generated by scripts/plan_batches.py — do not hand-edit.')
    out.append('# Cost model: mopac ~ N^2 * pm7_steps; pyscf ~ N^4 * paper_steps.')
    for solver in solvers:
        bins, totals, nbins = plan(reference, solver, nbins_arg)
        mean = sum(totals) / nbins
        spread = (max(totals) - min(totals)) / mean if mean else 0.0
        out.append(
            f'# {solver}: {nbins} batches, ' f'cost spread = {spread:.0%} of mean'
        )
        for i, names in enumerate(bins):
            mols = ' '.join(names)
            out.append(
                f'- {{ solver: {solver}, batch_id: b{i}, molecules: {mols} }}'
            )
    return '\n'.join(out) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--reference', type=Path, default=REFERENCE)
    ap.add_argument('--solvers', nargs='+', default=['mopac', 'pyscf'])
    ap.add_argument(
        '--nbins',
        type=int,
        default=None,
        help='override per-solver bin count (default: ceil(total/max_single))',
    )
    args = ap.parse_args(argv)
    reference = json.loads(args.reference.read_text())
    print(emit(reference, args.solvers, args.nbins), end='')


if __name__ == '__main__':
    main()
