name: Tests
on: [push, pull_request]
jobs:
  all:
    name: All
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MOPAC
        run: |
          mkdir mopac
          cd mopac
          wget -q https://github.com/openmopac/mopac/releases/download/v${MOPAC_VERSION}/mopac-${MOPAC_VERSION}-linux.tar.gz
          tar --strip-components=1 -xzf mopac-${MOPAC_VERSION}-linux.tar.gz
          echo "$PWD/bin" >>$GITHUB_PATH
          echo "LD_LIBRARY_PATH=$PWD/lib" >>$GITHUB_ENV
        env:
          MOPAC_VERSION: 23.2.5
      - name: Install
        run: pip install -e ".[test]"
      - name: Test
        run: coverage run -m pytest -v
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
